# Generated by Django 4.0.2 on 2022-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shu_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('shu_id',)},
        ),
    ]
