# Generated by Django 4.0.2 on 2022-03-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_alter_user_unique_together_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date_time', models.DateTimeField()),
                ('event_place', models.TextField()),
            ],
            options={
                'unique_together': {('event_id',)},
            },
        ),
    ]
