# Generated by Django 4.0.2 on 2022-03-08 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='studentsapp.events')),
                ('student_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
