# Generated by Django 4.0.2 on 2022-03-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0004_eventsregistered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=50)),
                ('game_date_time', models.DateTimeField()),
                ('game_place', models.TextField()),
            ],
            options={
                'unique_together': {('game_id',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventsregistered',
            unique_together={('event_id', 'student_id')},
        ),
        migrations.CreateModel(
            name='SportsRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='studentsapp.sports')),
                ('student_id', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sport_id', 'student_id')},
            },
        ),
    ]
