# Generated by Django 4.0.2 on 2022-03-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0005_sports_alter_eventsregistered_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sports',
            old_name='game_date_time',
            new_name='sport_date_time',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='game_id',
            new_name='sport_id',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='game_name',
            new_name='sport_name',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='game_place',
            new_name='sport_place',
        ),
        migrations.AlterUniqueTogether(
            name='sports',
            unique_together={('sport_id',)},
        ),
    ]
