# Generated by Django 4.0.2 on 2022-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0006_rename_game_date_time_sports_sport_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_count', models.IntegerField(default=0)),
                ('gender_type', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('any', 'any')], default='-', max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
            ],
        ),
    ]
