# Generated by Django 4.0.2 on 2022-03-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0007_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='gender_type',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('any', 'any')], max_length=500),
        ),
    ]
