# Generated by Django 4.0.2 on 2022-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0008_accommodation_user_alter_accommodation_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
